; PlatformIO Project Configuration File
; Projet : living-lab-sensors - ESP32 pour aquaponie
; Framework : Arduino
; Licence : MIT

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Vitesse de communication série
monitor_speed = 115200
upload_speed = 921600

; Bibliothèques nécessaires
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21
    adafruit/Adafruit Unified Sensor @ ^1.1

; Options de compilation
build_flags =
    -I include
    -Wall
    -Wextra

; Port série automatique (Windows / Linux / Mac)
; upload_port = COM3   (décommentez et adaptez si besoin)
